### ISSUE TITLE
move static overrides int othe constructor?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/fields_generator#49]
I'm not a big fan of our stubs returning the super verbose `public $static` everything with the comments etc.

I was messing around with extending an importer and took this approach: overriding the parent static methods in the `__construct` method:

```php

  /**
   * how we previously set it.  no longer necessary, you get style complaints.
   */
  public static $methods = array(
    'file_upload' => FALSE,
    'file_local' => FALSE,
    'file_remote' => FALSE,
  );
  public static $file_required = FALSE;

  /**
   * EutilsImporter constructor.
   *
   * @param \TripalJob|null $job
   */
  public function __construct(TripalJob $job = NULL) {
    parent::__construct($job);
    static::$name = 'NCBI EUtils Accession loader';
    static::$machine_name = 'eutils_loader';
    static::$description = 'Import a BLAST XML file into Chado';
    static::$use_analysis = FALSE;
    static::$button_text = 'Import NCBI Record';
    static::$methods = [
      'file_upload' => FALSE,
      'file_local' => FALSE,
      'file_remote' => FALSE,
    ];
  }
```

Do we like this more?  You get a *lot* of less code sniffer complaints this way and its a lot more compact.

I also think it will partially resolve #46

**Comment by bradfordcondon** [comment]
this doesnt work for the importer because those values are used before its instantiated.

If its a problem for improters, its probably also a problem for fields.

**Comment by almasaeed2010** [comment]
You are correct. Static variables are accessed before instantiation and therefore we can't do this.
